# Generated by Django 4.2 on 2023-04-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tttwars', '0002_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
