# Generated by Django 4.2 on 2023-04-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tttwars', '0008_remove_tttwarsgame_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tttwarsgame',
            name='board',
            field=models.JSONField(default=[[0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0]]),
        ),
    ]
