# Generated by Django 4.2 on 2023-04-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tttwars', '0009_tttwarsgame_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='tttwarsgame',
            name='movecount',
            field=models.IntegerField(default=0),
        ),
    ]
