# Generated by Django 4.2 on 2023-04-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tttwars', '0010_tttwarsgame_movecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='tttwarsgame',
            name='dscore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tttwarsgame',
            name='oscore',
            field=models.IntegerField(default=0),
        ),
    ]
