# Generated by Django 4.2 on 2023-04-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tttwars', '0011_tttwarsgame_dscore_tttwarsgame_oscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='tttwarsgame',
            name='dmatchscore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tttwarsgame',
            name='omatchscore',
            field=models.IntegerField(default=0),
        ),
    ]
