# Generated by Django 4.2 on 2023-04-24 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tttwars', '0012_tttwarsgame_dmatchscore_tttwarsgame_omatchscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='tttwarsgame',
            name='gamenumber',
            field=models.IntegerField(default=1),
        ),
    ]
