# Generated by Django 4.2 on 2023-04-25 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tttwars', '0015_tttwarsgame_dgame1score_tttwarsgame_dgame2score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tttwarsgame',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
