# Generated by Django 4.2 on 2023-04-25 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tttwars', '0016_tttwarsgame_started'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tttwarsgame',
            old_name='dmatchscore',
            new_name='matchscore1',
        ),
        migrations.RenameField(
            model_name='tttwarsgame',
            old_name='omatchscore',
            new_name='matchscore2',
        ),
    ]
