# Generated by Django 4.2 on 2023-04-25 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tttwars', '0017_rename_dmatchscore_tttwarsgame_matchscore1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tttwarsgame',
            old_name='offense',
            new_name='p1',
        ),
        migrations.RenameField(
            model_name='tttwarsgame',
            old_name='defense',
            new_name='p2',
        ),
    ]
